# Generated by Django 3.2.9 on 2021-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(max_length=100, verbose_name='Atayan Kişi')),
                ('task_name', models.CharField(max_length=100, verbose_name='Görev İsmi')),
                ('priority', models.CharField(choices=[('Acil', 1), ('Önemli', 2), ('Az Önemli', 3)], max_length=100, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('Bekleniyor', 1), ('İşleme Alındı', 2), ('Revize Verildi', 3)], max_length=100, verbose_name='Durum')),
                ('due_date', models.DateTimeField(verbose_name='Termin Tarihi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Veriliş Tarihi')),
            ],
            options={
                'verbose_name': 'Görevler',
                'verbose_name_plural': 'Görevler',
            },
        ),
    ]
