# Generated by Django 3.2.9 on 2021-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Kullanıcı')),
                ('assignee', models.CharField(max_length=100, verbose_name='Atayan Kişi')),
                ('task_name', models.CharField(max_length=100, verbose_name='Görev İsmi')),
                ('email', models.CharField(default='weveyej837@healteas.com', max_length=255, verbose_name='Email')),
                ('due_date', models.DateField(verbose_name='Termin Tarihi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Veriliş Tarihi')),
            ],
            options={
                'verbose_name': 'Görevler',
                'verbose_name_plural': 'Görevler',
            },
        ),
    ]
