# Generated by Django 3.2.9 on 2021-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[(1, 'Acil'), (2, 'Önemli'), (3, 'Az Önemli')], max_length=100, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[(1, 'Bekleniyor'), (2, 'İşleme Alındı'), (3, 'Revize Verildi')], max_length=100, verbose_name='Durum'),
        ),
    ]
