# Generated by Django 3.2.9 on 2021-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211110_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('Acil', 1), ('Önemli', 2), ('Az Önemli', 3)], max_length=100, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Bekleniyor', 1), ('İşleme Alındı', 2), ('Revize Verildi', 3)], max_length=100, verbose_name='Durum'),
        ),
    ]
